-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categorias
(
    id bigint,
    nombre text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id bigint,
    nombre text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    categoria_id bigint,
    "codigoSku" text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.stocks
(
    id bigint,
    precio numeric(12, 4),
    cantidad integer,
    producto_id bigint
);

ALTER TABLE IF EXISTS public.productos
    ADD FOREIGN KEY (categoria_id)
    REFERENCES public.categorias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stocks
    ADD FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;